# fly.toml app configuration file generated for onlinenotepad-secsync-late-butterfly-7641 on 2025-02-27T14:53:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'onlinenotepad-secsync-late-butterfly-7641'
primary_region = 'ams'
swap_size_mb = 2048

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = 'npm run prisma:prod:migrate'

[env]
  PORT = '8080'
  secrets = 'map[DATABASE_URL:DATABASE_URL]'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
