# fly.toml app configuration file generated for secsync on 2023-06-27T11:49:39+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "secsync"
primary_region = "ams"

[deploy]
  release_command = "yarn prisma:prod:migrate"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
